### ISSUE TITLE
Shortcuts when input is focused

### ISSUE THREAD

**Issue by pdonias** [avocode/react-shortcuts#10]
When an input is focused, the shortcuts don't work, which is quite normal when you want to type something in a text input.
But when the input is a checkbox, I would like the shortcuts to work.

Is there any way to do it?

**Comment by petrbrzek** [comment]
@pdonias We could probably add a custom data attribute (e.g `data-shortcuts="true"`), so React Shortcuts would fire the callback. What do you think?

**Comment by julien-f** [comment]
IMHO, it does not make sense for shortcuts to be inhibited on checkbox/radio inputs, and it would be best to change this behavior directly in react-shortcuts :)

**Comment by petrbrzek** [comment]
@julien-f not sure about it. Default behavior like pressing space to check/uncheck won't work.

**Comment by julien-f** [comment]
Unless there are no shortcuts defined for space, no?

**Comment by cadavre** [comment]
But sometimes handling shortcuts are needed in inputs. Take as an example when you define global shortcuts for your application, like "open modal menu". Then it's impossible to achieve while you're in input. We definitely want react-shortcuts listening also inside of inputs!

**Comment by forum-is** [comment]
We are using react-shortcuts in a commercial document management application where our main views consist of form-like pages with mostly (text-)inputs. With the current behavior, a global Ctrl+S** save-hook will only trigger when our customers have either: 
- just activated the editMode of a document and no input has been focussed (when saving does not make sense)
- clicked somewhere outside of an input field *before* pressing the shortcut (meaning they could just aswell click the save-button, making the shortcut obsolete)

Pressing Ctrl+S while inside an input field will default to the browser's "Save page..." hook, which breaks the UX.

Changing the global-Property on respective shortcuts will have no effect whatsoever. 

We would expect that at least for *global* shortcuts the key event would bubble up from inputs to shortcuts *if* a respective shortcut is registered.

@petrbrzek IMHO Default behavior should win as long as there is no (global) overriding shortcut for exactly that respective key combination. If one were to register a SPACE-shortcut on a checkbox input and hence override the default toggling behavoir, that would be at one's own responsibility. Naturally, registering one specific shortcut should not prevent any other key-events on an input.

**Comment by petrbrzek** [comment]
@forum-is Would adding the property in this pull request #23 solved the issue for you?

**Comment by forum-is** [comment]
@petrbrzek Ported the changes to the the shortcuts.js in our node_modules, gave the Shortcuts an alwaysFireHandler={true} and it seems to work (tested with textareas and regular text-input).

A problem that remains is that react-shortcuts seems to break special key handlers of the react-select-plus module we are using for ComboBoxes. Therein the up and down arrow keys should be overloaded to move around in the available options of the combobox. Since we added react-shortcuts, those are blocked and default to the regular input-behavior (jump to start or end of current text inside). The keybindings are defined within the module (possibly by other means) and are therefor out of our reach.

Any idea for a workaround or approach to "blacklisting" overrides of certain keyhandlers that are not provided via Shortcut?

**Comment by petrbrzek** [comment]
@forum-is We released 1.4.0 version on NPM.

> A problem that still remains is that react-shortcuts seems to break special key handlers of the react-select-plus module we are using for ComboBoxes. Therein the up and down arrow keys should move around in the available options of the (custom rendered) combobox while focussing the control's input (which is basically a text input with custom handlers attached).

For this case you can set `isolate={true}` prop on higher `<Shortcuts>` component. So the React events used in react-select-plus will fire.

> Out of curiosity: What is the purpose of isReturnString?

This is used for the case when you type in an input or textarea and only non printable keys will fire the Shortcuts's callback. So if you write `abc` nothing will be fired but if you press `CTRL` key, it fires.

**Comment by forum-is** [comment]
Thank you very much, now everything works fine! =)
