### ISSUE TITLE
Focused input-field doesn't prevent shortcuts

### ISSUE THREAD

**Issue by bunterWolf** [avocode/react-shortcuts#13]
My shortcuts (arrow left, right...)  are executing even if an input field is focused. 
How can I avoid that?

I can't stop the onKeyDown on the input directly, because with the Shortcuts Component as a parent no react keyEvent is firing anymore.

Here it sound right, do I something wrong? https://github.com/avocode/react-shortcuts/issues/10

**DomRender**
```
      <ShortcutSetup shortcutManager={shortcutManager}>  
          <Shortcuts name="App" handler={handle}>  
            <div><input onKeyPress={  
              (event) => {  
                // Not Executing  
              }  
            } /></div>  
          </Shortcuts>    
      </ShortcutSetup>  
```

**ShortcutSetup**
```
export default class ShortcutSetup extends React.Component {
  constructor(props) {super(props)}

  render() {
    return(
      <div>{this.props.children}</div>
    )
  }

  getChildContext = function () {
    return {
      shortcuts: this.props.shortcutManager
    }
  }
}

ShortcutSetup.childContextTypes = {
  shortcuts: React.PropTypes.object.isRequired
}
```

merci!

**Comment by bunterWolf** [comment]
**My dirty fix:** :)

```
export function shortcutHandler(action, event) {
  if( event.target.tagName.toUpperCase() == 'INPUT' ) {
    return
  }
  ...
}
```

**Comment by julien-f** [comment]
@bunterWolf Do you use Safari?

**Comment by petrbrzek** [comment]
@bunterWolf If an input is focused React Shortcuts doesn't fire only if the corresponding event's key is printable (so callback won't fire for keys like `a, b, c, ...` but fires for `arrow keys, ctrl, etc..`). Is this a problem for your use case? You can also use `isolate={true}` prop, so your `onKeyPress` handler would fire.

**Comment by bunterWolf** [comment]
ah merci, did not get meaning of isolate from the docu by reading the first time.. :)
But my fix is for me slightly more useful and I can do something like this: 

```
<Shortcuts name="global"> 
// Global Ignore Events from Input
// navigation arrowUp, down, Shortcuts: ctrl+a ......
  react-components...
  <FileComponent>
    <Shortcuts name="renameInput">
    // Rename Input Shortcuts: Does not ignore Input Events 
    // Handels: Esc, Enter -> Save, Cancel
      <input>
    </Shortcuts>
  </FileComponent>
</Shortcuts>
```

**Comment by petrbrzek** [comment]
@bunterWolf Nice. So can we close the issue now?
