### ISSUE TITLE
The reason for Mousetrap?

### ISSUE THREAD

**Issue by bunterWolf** [avocode/react-shortcuts#15]
I try to setup a relative complex keyhandling for an filemanager with electron. 
And i'm still researching... not an easy topic :)

You and react-hotkeys decided both for using Mousetrap and I would like to understand the reason for that:)

The negative side of Mousetrap is, that you loose the control on the keyboard Event Handling in react, because Mousetrap handles events. (You can get them in react with isolate=true (greate!), but you are handling them still after Mousetrap did already something)

Mousetrap does the mapping of the Shortcut-Strings 'ctrl+alt+i' and the keyboard-event. But to build that for react events looks easy to me right know.

What do I miss? :)

merci!

**Comment by petrbrzek** [comment]
@bunterWolf You are right. We are actually using Combokeys but it's the same story. The reason is simple, we are using it because it's good enough and reimplement it to React is not a priority right now. But yeah it would be better.

**Comment by bunterWolf** [comment]
ok, thank! :)
