### ISSUE TITLE
Auto-focus component

### ISSUE THREAD

**Issue by ernoaapa** [avocode/react-shortcuts#18]
Hi!
Thanks for nice and clean library!

I'm having problem to find out how to make it automatically focus to the element so that user don't need to click inside element before shortcuts start to work.
For example in the [demo](http://avocode.github.io/react-shortcuts/) after page is loaded, right and left arrows don't do anything until I first click one of the element.

Is it possible to automatically focus to the element? Thanks!

**Comment by petrbrzek** [comment]
Hello @ernoaapa,

Auto-focus is not handled by React Shortcuts. I don't think it should be part of this library as it can easily be achieved by your own HOC component. Closing the issue now.
