### ISSUE TITLE
Need to be able to handle shortcuts even if focus is on an input element

### ISSUE THREAD

**Issue by bradbirnbaum** [avocode/react-shortcuts#19]
Often you need to have global shortcuts that will be propagated even if we are typing in an input or contentEditable element.  As an example in the browser if I an in an input and type `cmd+w` it will still close my browser window.   I believe this we need to have a prop that is used here https://github.com/avocode/react-shortcuts/blob/master/src/component/shortcuts.js#L112 so that we can ignore returning false.

**Comment by petrbrzek** [comment]
If you want to have global shortcuts then just add `global={true}` prop to appropriate `<Shortcuts>`. It'll fire the callback handler even if focus is on input like element.

**Comment by bradbirnbaum** [comment]
Thanks for the quick response.   I didn't find that to be the case.   I was seeing `stopCallback` returning `true`
