### ISSUE TITLE
Keymap is in your console

### ISSUE THREAD

**Issue by mark0978** [avocode/react-shortcuts#22]
In v55 of Chrome on mac I have no keymap in the console on your demo (and the HMR stuff keeps trying to hit localhost:8080

**Comment by dmi3y** [comment]
They are literally into the console as logged object which has to be expanded:
![screen shot 2017-05-24 at 11 15 32 pm](https://cloud.githubusercontent.com/assets/1277279/26438340/47a5de92-40d7-11e7-821f-5f79fe2f19bc.png)

**Comment by petrbrzek** [comment]
There is a new demo available https://codesandbox.io/s/l40jjo48nl. Closing this.

**Comment by mark0978** [comment]
New demo is much better and usable out of the box.
If I were going to say the Keymap is in the console, I'd have done some work to actually log it for humans instead of hiding under a collapsed object.  (2 levels deep I might add, neither of which were named Keymap....)
