### ISSUE TITLE
Too big

### ISSUE THREAD

**Issue by googol7** [avocode/react-shortcuts#24]
webpack-bundle-size-analyzer reports that react-shortcuts adds 543.08 KB to my bundle (before compressing):

```
react-shortcuts: 543.08 KB (18.7%)                                                      
  lodash: 526.94 KB (97.0%)
  <self>: 16.14 KB (2.97%)
```

**Comment by petrbrzek** [comment]
Wow, thanks for noticing me. I can cherry pick only those functions we use from lodash. Will do.
