### ISSUE TITLE
tabIndex={0} doesn't work

### ISSUE THREAD

**Issue by clausman** [avocode/react-shortcuts#34]
Looks like `shortcuts.js` uses a truthy check to default to index of -1 rather than a null check. This means that it's impossible to set the tabindex to 0 so the shortcuts uses the pages tab order. In particular, I believe this line is the culprit:

https://github.com/avocode/react-shortcuts/blob/master/src/component/shortcuts.js#L73

**Comment by clausman** [comment]
can be worked around with a very loud propTypes console error if you use `tabIndex={"0"}` since that will paths the truthy check and therefore not use the default -1 value.

**Comment by petrbrzek** [comment]
@clausman Good catch. Will fix it now.
