### ISSUE TITLE
Only get event when focus on component

### ISSUE THREAD

**Issue by jvanhent** [avocode/react-shortcuts#36]
Hi,

I have an application with different components, each containing again other components.
I have propagated the childContext up to my Component containing a Button.
This button is wrapped in a <Shortcuts> tag.

In my react developer tools I get confirmation that my ShortcutManager is indeed in the context of <Shortcuts>.

I have added ctrl+n in the keymap. This event should be sent to my component no mather where the focus is on my Application.

Ctrl+n only seems to work when I have focus on the button inside <Shortcuts>.

I tried to set the shortcut as global, but doesn't work...

Is it possible to get events without focus on a component?

Thanks

**Comment by roelofvkr** [comment]
I'm having the same issue, did you find a fix for this?

**Comment by jvanhent** [comment]
I use directly mousetrap and mouse-trap-global now.
So bind and unbind on mount and unmount

**Comment by petrbrzek** [comment]
You should use targetNodeSelector for this use case.
