### ISSUE TITLE
Unrecognized tag: shortcuts

### ISSUE THREAD

**Issue by w33ble** [avocode/react-shortcuts#39]
The [shortcuts component](https://github.com/avocode/react-shortcuts/blob/master/src/component/shortcuts.js#L222) uses a `<shortcuts>` tag to wrap the children. As a result, I get the following error from React:

> Warning: The tag <shortcuts> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.

Is there a reason this isn't a div or some other recognized tag? Can it just be a div with maybe a shortcuts class?

I'm running React 16 rc3, and I've seen this message since rc1. Other than that message, everything seems to work great in v16.

**Comment by Asp3ctus** [comment]
I have created a pull request, i have tested it on react react@16.0.0-rc.3 and it works
