### ISSUE TITLE
npm install fails when not in git repo

### ISSUE THREAD

**Issue by liebald** [avocode/react-shortcuts#5]
Installing react-shortcuts on Heroku fails with the following error when running the postinstall step:

remote:        > react-shortcuts@0.7.2 postinstall /tmp/build_873459873ebc1028923e151fdfb86472/node_modules/react-shortcuts
remote:        > git clean -f -d
remote:
remote:        fatal: Not a git repository (or any parent up to mount point /tmp)
remote:        Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

I can replicate this when trying to install the package in non-git directory on my local workstation. What's the purpose of running this command as the postinstall script, and could it be made to fail gracefully outside of git repositories?

**Comment by petrbrzek** [comment]
It cleans out js files from root folder. I removed it in ba3358cf6fb95d5457de9e28c49ce7e43483f073.

**Comment by liebald** [comment]
Thanks for the quick fix and for updating the NPM package!
