### ISSUE TITLE
Abilityt to add shortcuts ad-hoc

### ISSUE THREAD

**Issue by raybooysen** [avocode/react-shortcuts#50]
At the moment the docs state:

```
import keymap from './keymap'
import { ShortcutManager } from 'react-shortcuts'

const shortcutManager = new ShortcutManager(keymap)

// Or like this

const shortcutManager = new ShortcutManager()
shortcutManager.setKeymap(keymap)
```

How can a developer add keymaps during the runtime of an application.  There may be new keymaps coming in.  Aside from keeping our own cache of the full keymap, it would be nice to have something like:

```
shortcutManager.updateKeyMap(additionalMaps);
```

**Comment by petrbrzek** [comment]
@raybooysen You can call `shortcutManager.extendKeymap(keymap)`. We'll improve documentation by merging #46.

**Comment by raybooysen** [comment]
Thank you!
